#pragma once

/*==========================*/
/*=== SPRITE DEFINITIONS ===*/
/*==========================*/
	//Background Sprites
	#define BACKGROUND_FOREST 1

	//Interface Sprites
	#define SPRITE_INTERFACE_OPTIONS 1
	#define SPRITE_INTERFACE_MESSAGE 2
	#define SPRITE_INTERFACE_KEYBOARD 3
	#define SPRITE_INTERFACE_LOGIN 4
	#define SPRITE_INTERFACE_RADAR 5
	#define SPRITE_INTERFACE_ARROW 6
	#define SPRITE_INTERFACE_BAR_EL 7
	#define SPRITE_INTERFACE_BAR_EC 8
	#define SPRITE_INTERFACE_BAR_ER 9
	#define SPRITE_INTERFACE_BAR_RL 10
	#define SPRITE_INTERFACE_BAR_RC 11
	#define SPRITE_INTERFACE_BAR_RR 12
	#define SPRITE_INTERFACE_MAP_DOT 13
	#define SPRITE_INTERFACE_BAR_YL 14
	#define SPRITE_INTERFACE_BAR_YC 15
	#define SPRITE_INTERFACE_BAR_YR 16
	#define SPRITE_INTERFACE_BAR_BL 17
	#define SPRITE_INTERFACE_BAR_BC 18
	#define SPRITE_INTERFACE_BAR_BR 19
	#define SPRITE_INTERFACE_BOX_BC 20
	#define SPRITE_INTERFACE_BOX_BH 21
	#define SPRITE_INTERFACE_BOX_BV 22

	//Button Sprites
	#define SPRITE_BUTTON_STORY 2
	#define SPRITE_BUTTON_MULTIPLAYER 4
	#define SPRITE_BUTTON_OPTIONS 6
	#define SPRITE_BUTTON_CREDITS 8
	#define SPRITE_BUTTON_QUIT 10
	#define SPRITE_BUTTON_OKAY 12
	#define SPRITE_BUTTON_LOGIN 14
	#define SPRITE_BUTTON_DONE 16
	#define SPRITE_BUTTON_CONTROLS 18
	#define SPRITE_BUTTON_KEYPICK 20
	#define SPRITE_BUTTON_CANCEL 22
	#define SPRITE_BUTTON_CONTINUE 24
	#define SPRITE_BUTTON_RES 26

	//Tile Sprites
	#define SPRITE_TILE_GRASS_T1 0

	//Other Sprites
	#define NO_SPRITE 0
	#define SPRITE_CURSOR 1
	#define SPRITE_ICON DE_CONFIG_ICON
	#define SPRITE_INTERFACE_CONNECTING 3
	#define SPRITE_LOGO 4

/*=========================*/
/*= INTERFACE DEFINITIONS =*/
/*=========================*/
	#define FADE_OUT 0
	#define FADE_IN 1
	#define INTERFACE_MAIN_MENU 0
	#define INTERFACE_OPTIONS 3
	#define INTERFACE_VERSION 6
	#define INTERFACE_LOGIN 8
	#define INTERFACE_KEYBOARD 9
	#define INTERFACE_PAUSE 10
	#define INTERFACE_CREDITS 11
	#define INTERFACE_RADAR 12
	#define INTERFACE_STATS 13
	#define INTERFACE_MINI_MAP 14
	#define INTERFACE_CHAT 29
	#define INTERFACE_SCORE 30
	#define INTERFACE_MESSAGE 99